language: scala
matrix:
  include:
    - os: linux
      jdk: oraclejdk9
      scala: 2.12.4
      addons:
        apt:
          packages:
            - oracle-java9-installer # Forces use of newer JDK 9 build
    - os: linux
      jdk: openjdk8
      scala: 2.12.4
    - os: linux
      jdk: oraclejdk8
      scala: 2.11.12
script:
  - sbt -no-colors ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport mimaReportBinaryIssues
after_success:
  - bash <(curl -s https://codecov.io/bash)
